=head1 NAME

Any::Image -

=head1 SYNOPSIS

  use Any::Image;

=head1 DESCRIPTION

Any::Image is

=head1 AUTHOR

Masahiro Chiba E<lt>nihen@megabbs.comE<gt>

=head1 SEE ALSO

=head1 LICENSE

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.


=cut

